apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-user
  template:
    metadata:
      labels:
        app: microservice-user
    spec:
      containers:
        - name: microservice-user
          image: 122610500465.dkr.ecr.us-east-2.amazonaws.com/repository-teste:latest
          ports:
            - containerPort: 8080