apiVersion: v1
kind: Service
metadata:
  name: microservice-user-service
spec:
  type: LoadBalancer
  selector:
    app: microservice-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080