apiVersion: v1
kind: Service
metadata:
  name: microservice-user-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-012f84750aa8e28d3,subnet-0beb77931365c5181
spec:
  type: LoadBalancer
  selector:
    app: microservice-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080