apiVersion: v1
kind: Service
metadata:
  name: microservice-user-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-08faf4d600d843ff7,subnet-01b718057b6ebf8fc,subnet-0e75dae16c580f742
spec:
  type: LoadBalancer
  selector:
    app: microservice-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080